return {
  -- 'David-Kunz/gen.nvim',
  -- lazy = false,
  -- config = function()
  --   local opts = {
  --     model = 'llama3.1', -- The default model to use.
  --     display_mode = 'split', -- The display mode. Can be "float" or "split" or "horizontal-split".
  --     show_prompt = false, -- Shows the prompt submitted to Ollama.
  --     show_model = true, -- Displays which model you are using at the beginning of your chat session.
  --     no_auto_close = false, -- Never closes the window automatically.
  --     hidden = false, -- Hide the generation window (if true, will implicitly set `prompt.replace = true`)
  --   }
  --   require('gen').setup(opts)
  --
  --   local prompts = require('gen').prompts
  --   prompts['Enhance Quarto code'] = {
  --     prompt = 'Enhance the following code and prose if applicable. ONLY output the enhanced output, do NOT give any'
  --       .. 'explanations of what you changed or why, this is very important.\n\n$text',
  --     replace = true,
  --   }
  -- end,
}
