return {
  -- 'nomnivore/ollama.nvim',
  -- dependencies = {
  --   'nvim-lua/plenary.nvim',
  -- },
  --
  -- -- All the user commands added by the plugin
  -- cmd = { 'Ollama', 'OllamaModel', 'OllamaServe', 'OllamaServeStop' },
  --
  -- ---@type Ollama.Config
  -- opts = {
  --   model = 'llama3.1',
  --   prompts = {
  --     Enhance_Quarto_selection = {
  --       prompt = 'Enhance the following code and prose if applicable. ONLY output the enhanced output, do NOT give any'
  --         .. 'explanations of what you changed or why, this is very important.\n\n$sel',
  --       action = 'display_replace',
  --       extract = '.*',
  --     },
  --     Enhance_Quarto_buffer = {
  --       prompt = 'Enhance the following code and prose if applicable. ONLY output the enhanced output, do NOT give any'
  --         .. 'explanations of what you changed or why, this is very important.\n\n$buf',
  --       action = 'display_replace',
  --       extract = '.*',
  --     },
  --     -- Sample_Prompt = {
  --     --   prompt = 'This is a sample prompt that receives $input and $sel(ection), among others.',
  --     --   input_label = '> ',
  --     --   model = 'mistral',
  --     --   action = 'display',
  --     -- },
  --   },
  -- },
}
